export enum ENUM_IT_STRINGS {
    privacyNotice = "Prendi un momento per consultare la nostra normativa sulla privacy prima di rispondere a questo questionario",
    startButtonText = "Inizia",
    sendButtonText = "invia",
    skipButtonText = "salta",
    restartButtonText = "Ricomincia",
    continueButtonText = "Continua",
    endButtonText = "Fatto",
    endScreenButtonText = "Mostra chat",
    doneConversation = "Sembra che stessimo già avendo questa conversazione...",
    endScreenText = "Ora puoi chiudere questa pagina 😊",
    consentText = "*premendo su INIZIA, confermi di essere informato e di voler rispondere alle domande di questo questionario.",
    cookieText = "Ciao! Vorremmo usare dei cookie per migliorare la tua esperienza, ma ci serve il tuo consenso per farlo",
    readMoreButtonText = "Leggi di più",
    cookieAgreeButton = "Accetta",
    wrongLinkText = "Ci spiace, il link è scaduto oppure incompleto.",
    unableToLoadChatText = "Impossibile caricare la chat, il link è scaduro oppure incompleto.",
    somethingWrongText = "Qualcosa è andato storto...",
    noSurveyChosenText = "Nessuna conversatione selezionata",
    surveyAlreadyCompetedText = "Hai già compilato questo questionario",
    noPublishedSurvey = "Mi spiace, non ho trovato nessun questionario disponibile",
}

export enum ENUM_EN_STRINGS {
    privacyNotice = "Please take a moment to review our policy prior to answering the survey questions",
    startButtonText = "Start",
    sendButtonText = "send",
    skipButtonText = "skip",
    restartButtonText = "Restart",
    continueButtonText = "Continue",
    endButtonText = "Done",
    endScreenButtonText = "Show Chat",
    doneConversation = "It looks like we were already having this conversation...",
    endScreenText = "You can now close this page 😊",
    consentText = "*by clicking START, you consent that you are informed and willing to answer the questions in this survey.",
    cookieText = "Hi! We'd like to use cookies to enhance your experience, but we need your consent to do so.",
    readMoreButtonText = "Read More",
    cookieAgreeButton = "Agree",
    wrongLinkText = "Sorry, either the link is expired or is missing some information...",
    unableToLoadChatText = "Couldn't load the chat. Either the link is expired or is missing some information...",
    somethingWrongText = "Something went wrong...",
    noSurveyChosenText = "No survey was chosen",
    surveyAlreadyCompetedText = "You have already completed this survey",
    noPublishedSurvey = "Sorry, I couldn't find any available surveys",
}
