FROM tomcat:8.5.43
COPY ./target/coney-api-0.1.war /usr/local/tomcat/webapps/coney-api.war
ENV NEO4J_URL http://neo4j:coney@coney-neo4j:7474
ENV RETE_PATH /opt/coney-data/
ENV SWAGGER_ENABLE true
EXPOSE 8080